# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chengshi.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow6(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.chengshi = QtWidgets.QComboBox(self.centralwidget)
        self.chengshi.setGeometry(QtCore.QRect(220, 140, 301, 22))
        self.chengshi.setObjectName("chengshi")
        self.chengshi.addItem("")
        self.chengshi.addItem("")
        self.chengshi.addItem("")
        self.chengshi.addItem("")
        self.chengshi.addItem("")
        self.chengshi.addItem("")
        self.chengshi.addItem("")
        self.chengshi.addItem("")
        self.chengshi.addItem("")
        self.chengshi.addItem("")
        self.chengshi.addItem("")
        self.chengshi.addItem("")
        self.chengshi.addItem("")
        self.chengshi.addItem("")
        self.chengshi.addItem("")
        self.chengshi.addItem("")
        self.chengshi.addItem("")
        self.chengshi.addItem("")
        self.chengshi.addItem("")
        self.chengshi.addItem("")
        self.chengshi.addItem("")
        self.chengshi.addItem("")
        self.chengshi.addItem("")
        self.chengshi.addItem("")
        self.chengshi.addItem("")
        self.chengshi.addItem("")
        self.chengshi.addItem("")
        self.chengshi.addItem("")
        self.chengshi.addItem("")
        self.chengshi.addItem("")
        self.chengshi.addItem("")
        self.chengshi.addItem("")
        self.chengshi.addItem("")
        self.queding_cheng = QtWidgets.QPushButton(self.centralwidget)
        self.queding_cheng.setGeometry(QtCore.QRect(290, 210, 171, 41))
        self.queding_cheng.setObjectName("queding_cheng")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.chengshi.setItemText(0, _translate("MainWindow", "北京"))
        self.chengshi.setItemText(1, _translate("MainWindow", "天津"))
        self.chengshi.setItemText(2, _translate("MainWindow", "石家庄"))
        self.chengshi.setItemText(3, _translate("MainWindow", "太原"))
        self.chengshi.setItemText(4, _translate("MainWindow", "呼和浩特"))
        self.chengshi.setItemText(5, _translate("MainWindow", "沈阳"))
        self.chengshi.setItemText(6, _translate("MainWindow", "长春"))
        self.chengshi.setItemText(7, _translate("MainWindow", "哈尔滨"))
        self.chengshi.setItemText(8, _translate("MainWindow", "上海"))
        self.chengshi.setItemText(9, _translate("MainWindow", "南京"))
        self.chengshi.setItemText(10, _translate("MainWindow", "杭州"))
        self.chengshi.setItemText(11, _translate("MainWindow", "合肥"))
        self.chengshi.setItemText(12, _translate("MainWindow", "福州"))
        self.chengshi.setItemText(13, _translate("MainWindow", "南昌"))
        self.chengshi.setItemText(14, _translate("MainWindow", "济南"))
        self.chengshi.setItemText(15, _translate("MainWindow", "郑州"))
        self.chengshi.setItemText(16, _translate("MainWindow", "武汉"))
        self.chengshi.setItemText(17, _translate("MainWindow", "长沙"))
        self.chengshi.setItemText(18, _translate("MainWindow", "广州"))
        self.chengshi.setItemText(19, _translate("MainWindow", "南宁"))
        self.chengshi.setItemText(20, _translate("MainWindow", "成都"))
        self.chengshi.setItemText(21, _translate("MainWindow", "贵阳"))
        self.chengshi.setItemText(22, _translate("MainWindow", "昆明"))
        self.chengshi.setItemText(23, _translate("MainWindow", "拉萨"))
        self.chengshi.setItemText(24, _translate("MainWindow", "西安"))
        self.chengshi.setItemText(25, _translate("MainWindow", "兰州"))
        self.chengshi.setItemText(26, _translate("MainWindow", "西宁"))
        self.chengshi.setItemText(27, _translate("MainWindow", "银川"))
        self.chengshi.setItemText(28, _translate("MainWindow", "乌鲁木齐"))
        self.chengshi.setItemText(29, _translate("MainWindow", "台北"))
        self.chengshi.setItemText(30, _translate("MainWindow", "大连"))
        self.chengshi.setItemText(31, _translate("MainWindow", "海口"))
        self.chengshi.setItemText(32, _translate("MainWindow", "重庆"))
        self.queding_cheng.setText(_translate("MainWindow", "确定"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow6()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

