# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tainanle.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow10(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(40, 180, 681, 161))
        self.groupBox.setStyleSheet("color: rgb(217, 23, 255);\n"
"font: 8pt \"楷体\";")
        self.groupBox.setObjectName("groupBox")
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(20, 50, 641, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(560, 110, 101, 41))
        self.pushButton.setObjectName("pushButton")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(40, 20, 681, 151))
        self.groupBox_2.setStyleSheet("color: rgb(217, 23, 255);\n"
"font: 8pt \"楷体\";")
        self.groupBox_2.setObjectName("groupBox_2")
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_2.setGeometry(QtCore.QRect(20, 50, 641, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_2.setGeometry(QtCore.QRect(560, 100, 101, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(290, 430, 251, 71))
        self.pushButton_3.setStyleSheet("color: rgb(205, 24, 255);\n"
"font: 8pt \"楷体\";")
        self.pushButton_3.setObjectName("pushButton_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "墙体结构"))
        self.comboBox.setItemText(0, _translate("MainWindow", "保温墙体(一)，保温材料：加气混凝土"))
        self.comboBox.setItemText(1, _translate("MainWindow", "保温墙体(一)，保温材料：水泥膨胀珍珠岩"))
        self.comboBox.setItemText(2, _translate("MainWindow", "保温墙体(一)，保温材料：沥青膨胀珍珠岩"))
        self.comboBox.setItemText(3, _translate("MainWindow", "保温墙体(二)，保温材料：沥青矿渣棉毡"))
        self.comboBox.setItemText(4, _translate("MainWindow", "保温墙体(二)，保温材料：塑料袋装膨胀蛭石"))
        self.comboBox.setItemText(5, _translate("MainWindow", "保温墙体(二)，保温材料：塑料袋装膨胀珍珠岩粉"))
        self.comboBox.setItemText(6, _translate("MainWindow", "保温墙体(二)，保温材料：沥青玻璃棉毡"))
        self.comboBox.setItemText(7, _translate("MainWindow", "保温墙体(二)，保温材料：塑料袋装脲醛泡沫塑料"))
        self.comboBox.setItemText(8, _translate("MainWindow", "保温墙体(三)，保温材料：沥青矿渣棉毡"))
        self.comboBox.setItemText(9, _translate("MainWindow", "保温墙体(三)，保温材料：塑料袋装膨胀蛭石"))
        self.comboBox.setItemText(10, _translate("MainWindow", "保温墙体(三)，保温材料：塑料袋装膨胀珍珠岩粉"))
        self.comboBox.setItemText(11, _translate("MainWindow", "保温墙体(三)，保温材料：沥青玻璃棉毡"))
        self.comboBox.setItemText(12, _translate("MainWindow", "保温墙体(三)，保温材料：塑料袋装脲醛泡沫塑料"))
        self.comboBox.setItemText(13, _translate("MainWindow", "砖墙"))
        self.comboBox.setItemText(14, _translate("MainWindow", "陶粒页岩混凝土大板280"))
        self.comboBox.setItemText(15, _translate("MainWindow", "混凝土、加气混凝土复合板240"))
        self.comboBox.setItemText(16, _translate("MainWindow", "填泡沫混凝土的钢筋混凝土墙板180"))
        self.comboBox.setItemText(17, _translate("MainWindow", "填泡沫混凝土的钢筋混凝土墙板220"))
        self.comboBox.setItemText(18, _translate("MainWindow", "膨珠混凝土大版280"))
        self.comboBox.setItemText(19, _translate("MainWindow", "混凝土、加气混凝土复合板280（一）"))
        self.comboBox.setItemText(20, _translate("MainWindow", "混凝土、加气混凝土复合板280（二）"))
        self.comboBox.setItemText(21, _translate("MainWindow", "纯加气混凝土大板"))
        self.comboBox.setItemText(22, _translate("MainWindow", "矿棉轻质复合板182"))
        self.comboBox.setItemText(23, _translate("MainWindow", "矿棉轻质复合板98"))
        self.comboBox.setItemText(24, _translate("MainWindow", "钢筋混凝土剪力墙"))
        self.pushButton.setText(_translate("MainWindow", "确定"))
        self.groupBox_2.setTitle(_translate("MainWindow", "屋顶结构"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "保温屋盖，保温材料：加气混凝土"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "保温屋盖，保温材料：水泥膨胀珍珠岩"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "保温屋盖，保温材料：沥青膨胀珍珠岩"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "通风屋盖，保温材料：加气混凝土"))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "通风屋盖，保温材料：水泥膨胀珍珠岩"))
        self.comboBox_2.setItemText(5, _translate("MainWindow", "通风屋盖，保温材料：沥青膨胀珍珠岩"))
        self.comboBox_2.setItemText(6, _translate("MainWindow", "吊顶屋盖(一)，保温材料：脲醛泡沫塑料"))
        self.comboBox_2.setItemText(7, _translate("MainWindow", "吊顶屋盖(一)，保温材料：膨胀珍珠岩粉"))
        self.comboBox_2.setItemText(8, _translate("MainWindow", "吊顶屋盖(一)，保温材料：沥青玻璃棉毡"))
        self.comboBox_2.setItemText(9, _translate("MainWindow", "吊顶屋盖(一)，保温材料：膨胀蛭石"))
        self.comboBox_2.setItemText(10, _translate("MainWindow", "吊顶屋盖(一)，保温材料：沥青矿渣棉毡"))
        self.comboBox_2.setItemText(11, _translate("MainWindow", "吊顶屋盖(二)，保温材料：脲醛泡沫塑料"))
        self.comboBox_2.setItemText(12, _translate("MainWindow", "吊顶屋盖(二)，保温材料：膨胀珍珠岩粉"))
        self.comboBox_2.setItemText(13, _translate("MainWindow", "吊顶屋盖(二)，保温材料：沥青玻璃棉毡"))
        self.comboBox_2.setItemText(14, _translate("MainWindow", "吊顶屋盖(二)，保温材料：膨胀蛭石"))
        self.comboBox_2.setItemText(15, _translate("MainWindow", "吊顶屋盖(二)，保温材料：沥青矿渣棉毡"))
        self.comboBox_2.setItemText(16, _translate("MainWindow", "吊顶屋盖(三)，保温材料：脲醛泡沫塑料"))
        self.comboBox_2.setItemText(17, _translate("MainWindow", "吊顶屋盖(三)，保温材料：膨胀珍珠岩粉"))
        self.comboBox_2.setItemText(18, _translate("MainWindow", "吊顶屋盖(三)，保温材料：沥青玻璃棉毡"))
        self.comboBox_2.setItemText(19, _translate("MainWindow", "吊顶屋盖(三)，保温材料：膨胀蛭石"))
        self.comboBox_2.setItemText(20, _translate("MainWindow", "吊顶屋盖(三)，保温材料：沥青矿渣棉毡"))
        self.pushButton_2.setText(_translate("MainWindow", "确定"))
        self.pushButton_3.setText(_translate("MainWindow", "完成"))

import wuding_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow10()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

